### PR TITLE
WEBEU2 - Node DB Challenge - James Eneh 🇳🇬

### PR DESCRIPTION
**Pull request by erozonachi**

### CODE REVIEW

**Review by delbaoliveira — COMMENTED** [review]
Good job James. Your review will be on your dashboard.

**Comment by erozonachi** [comment]
Thank you, Delba for the feedback...

There is an endpoint/route to add an action for a specific project @ api/projects/:id/actions (POST)

**Comment by erozonachi** [comment]
RE - GET api/projects/:id/actions endpoint is not working.

It's GET api/projects/:id  - NOT -  GET api/projects/:id/actions.

**Comment by delbaoliveira** [comment]
Hi James 👋 

Yes, I see the add actions endpoints now in the projects folder. Thank you for clarifying it! So you did reach MVP 🔥 

It also seems I did not use the correct endpoint when checking for the projects. Sorry about that 🙈 .  I'll amend your dashboard tomorrow so that the review is correct!

Great job on your project! And on defending it! 💯

**Pull request merged**
